/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class Age {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Age(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Age obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_Age(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Age(long initialAge, ageUnit_t initialUnits) {
    this(imebraJNI.new_Age(initialAge, initialUnits.swigValue()), true);
  }

  public double years() {
    return imebraJNI.Age_years(swigCPtr, this);
  }

  public void setAge(long value) {
    imebraJNI.Age_age_set(swigCPtr, this, value);
  }

  public long getAge() {
    return imebraJNI.Age_age_get(swigCPtr, this);
  }

  public void setUnits(ageUnit_t value) {
    imebraJNI.Age_units_set(swigCPtr, this, value.swigValue());
  }

  public ageUnit_t getUnits() {
    return ageUnit_t.swigToEnum(imebraJNI.Age_units_get(swigCPtr, this));
  }

}
