/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class DicomDictionary {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DicomDictionary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DicomDictionary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_DicomDictionary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String getUnicodeTagName(TagId id) {
    return imebraJNI.DicomDictionary_getUnicodeTagName(TagId.getCPtr(id), id);
  }

  public static String getTagName(TagId id) {
    return imebraJNI.DicomDictionary_getTagName(TagId.getCPtr(id), id);
  }

  public static tagVR_t getTagType(TagId id) {
    return tagVR_t.swigToEnum(imebraJNI.DicomDictionary_getTagType(TagId.getCPtr(id), id));
  }

  public static long getWordSize(tagVR_t dataType) {
    return imebraJNI.DicomDictionary_getWordSize(dataType.swigValue());
  }

  public static long getMaxSize(tagVR_t dataType) {
    return imebraJNI.DicomDictionary_getMaxSize(dataType.swigValue());
  }

  public DicomDictionary() {
    this(imebraJNI.new_DicomDictionary(), true);
  }

}
