/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public enum drawBitmapType_t {
  drawBitmapRGB(imebraJNI.drawBitmapType_t_drawBitmapRGB_get()),
  drawBitmapBGR(imebraJNI.drawBitmapType_t_drawBitmapBGR_get()),
  drawBitmapRGBA(imebraJNI.drawBitmapType_t_drawBitmapRGBA_get()),
  drawBitmapBGRA(imebraJNI.drawBitmapType_t_drawBitmapBGRA_get());

  public final int swigValue() {
    return swigValue;
  }

  public static drawBitmapType_t swigToEnum(int swigValue) {
    drawBitmapType_t[] swigValues = drawBitmapType_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (drawBitmapType_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + drawBitmapType_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private drawBitmapType_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private drawBitmapType_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private drawBitmapType_t(drawBitmapType_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

