/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class Groups {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Groups(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Groups obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_Groups(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Groups() {
    this(imebraJNI.new_Groups__SWIG_0(), true);
  }

  public Groups(long n) {
    this(imebraJNI.new_Groups__SWIG_1(n), true);
  }

  public long size() {
    return imebraJNI.Groups_size(swigCPtr, this);
  }

  public long capacity() {
    return imebraJNI.Groups_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    imebraJNI.Groups_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return imebraJNI.Groups_isEmpty(swigCPtr, this);
  }

  public void clear() {
    imebraJNI.Groups_clear(swigCPtr, this);
  }

  public void add(int x) {
    imebraJNI.Groups_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return imebraJNI.Groups_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    imebraJNI.Groups_set(swigCPtr, this, i, val);
  }

}
