/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public enum imageQuality_t {
  veryHigh(imebraJNI.imageQuality_t_veryHigh_get()),
  high(imebraJNI.imageQuality_t_high_get()),
  aboveMedium(imebraJNI.imageQuality_t_aboveMedium_get()),
  medium(imebraJNI.imageQuality_t_medium_get()),
  belowMedium(imebraJNI.imageQuality_t_belowMedium_get()),
  low(imebraJNI.imageQuality_t_low_get()),
  veryLow(imebraJNI.imageQuality_t_veryLow_get());

  public final int swigValue() {
    return swigValue;
  }

  public static imageQuality_t swigToEnum(int swigValue) {
    imageQuality_t[] swigValues = imageQuality_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (imageQuality_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + imageQuality_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private imageQuality_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private imageQuality_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private imageQuality_t(imageQuality_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

