/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class MemoryStreamInput extends BaseStreamInput {
  private transient long swigCPtr;

  protected MemoryStreamInput(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.MemoryStreamInput_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MemoryStreamInput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_MemoryStreamInput(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MemoryStreamInput(ReadMemory memory) {
    this(imebraJNI.new_MemoryStreamInput__SWIG_0(ReadMemory.getCPtr(memory), memory), true);
  }

  public MemoryStreamInput(ReadWriteMemory memory) {
    this(imebraJNI.new_MemoryStreamInput__SWIG_1(ReadWriteMemory.getCPtr(memory), memory), true);
  }

}
