/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class ReadWriteMemory extends ReadMemory {
  private transient long swigCPtr;

  protected ReadWriteMemory(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.ReadWriteMemory_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReadWriteMemory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_ReadWriteMemory(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ReadWriteMemory() {
    this(imebraJNI.new_ReadWriteMemory__SWIG_0(), true);
  }

  public ReadWriteMemory(long initialSize) {
    this(imebraJNI.new_ReadWriteMemory__SWIG_1(initialSize), true);
  }

  public ReadWriteMemory(ReadMemory sourceMemory) {
    this(imebraJNI.new_ReadWriteMemory__SWIG_2(ReadMemory.getCPtr(sourceMemory), sourceMemory), true);
  }

  public ReadWriteMemory(byte[] source) {
    this(imebraJNI.new_ReadWriteMemory__SWIG_3(source), true);
  }

  public void copyFrom(ReadMemory sourceMemory) {
    imebraJNI.ReadWriteMemory_copyFrom(swigCPtr, this, ReadMemory.getCPtr(sourceMemory), sourceMemory);
  }

  public void clear() {
    imebraJNI.ReadWriteMemory_clear(swigCPtr, this);
  }

  public void resize(long newSize) {
    imebraJNI.ReadWriteMemory_resize(swigCPtr, this, newSize);
  }

  public void reserve(long reserveSize) {
    imebraJNI.ReadWriteMemory_reserve(swigCPtr, this, reserveSize);
  }

  public void assign(byte[] source) {
    imebraJNI.ReadWriteMemory_assign(swigCPtr, this, source);
  }

  public void assignRegion(byte[] source, long destinationOffset) {
    imebraJNI.ReadWriteMemory_assignRegion(swigCPtr, this, source, destinationOffset);
  }

}
