/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class TagId {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TagId(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TagId obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_TagId(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TagId() {
    this(imebraJNI.new_TagId__SWIG_0(), true);
  }

  public TagId(int groupId, int tagId) {
    this(imebraJNI.new_TagId__SWIG_1(groupId, tagId), true);
  }

  public TagId(int groupId, long groupOrder, int tagId) {
    this(imebraJNI.new_TagId__SWIG_2(groupId, groupOrder, tagId), true);
  }

  public int getGroupId() {
    return imebraJNI.TagId_getGroupId(swigCPtr, this);
  }

  public long getGroupOrder() {
    return imebraJNI.TagId_getGroupOrder(swigCPtr, this);
  }

  public int getTagId() {
    return imebraJNI.TagId_getTagId(swigCPtr, this);
  }

}
