/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class TransformsChain extends Transform {
  private transient long swigCPtr;

  protected TransformsChain(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.TransformsChain_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TransformsChain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_TransformsChain(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TransformsChain() {
    this(imebraJNI.new_TransformsChain(), true);
  }

  public void addTransform(Transform transform) {
    imebraJNI.TransformsChain_addTransform(swigCPtr, this, Transform.getCPtr(transform), transform);
  }

}
