/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class TransformHighBit extends Transform {
  private transient long swigCPtr;

  protected TransformHighBit(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.TransformHighBit_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TransformHighBit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_TransformHighBit(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TransformHighBit() {
    this(imebraJNI.new_TransformHighBit(), true);
  }

}
