/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class VOILUT extends Transform {
  private transient long swigCPtr;

  protected VOILUT(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.VOILUT_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VOILUT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_VOILUT(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public VOILUT() {
    this(imebraJNI.new_VOILUT(), true);
  }

  public void applyOptimalVOI(Image inputImage, long topLeftX, long topLeftY, long width, long height) {
    imebraJNI.VOILUT_applyOptimalVOI(swigCPtr, this, Image.getCPtr(inputImage), inputImage, topLeftX, topLeftY, width, height);
  }

  public void setCenterWidth(double center, double width) {
    imebraJNI.VOILUT_setCenterWidth(swigCPtr, this, center, width);
  }

  public void setLUT(LUT lut) {
    imebraJNI.VOILUT_setLUT(swigCPtr, this, LUT.getCPtr(lut), lut);
  }

  public double getCenter() {
    return imebraJNI.VOILUT_getCenter(swigCPtr, this);
  }

  public double getWidth() {
    return imebraJNI.VOILUT_getWidth(swigCPtr, this);
  }

}
