/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class WritingDataHandler {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WritingDataHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WritingDataHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_WritingDataHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(long elementsNumber) {
    imebraJNI.WritingDataHandler_setSize(swigCPtr, this, elementsNumber);
  }

  public long getSize() {
    return imebraJNI.WritingDataHandler_getSize(swigCPtr, this);
  }

  public tagVR_t getDataType() {
    return tagVR_t.swigToEnum(imebraJNI.WritingDataHandler_getDataType(swigCPtr, this));
  }

  public void setSignedLong(long index, int value) {
    imebraJNI.WritingDataHandler_setSignedLong(swigCPtr, this, index, value);
  }

  public void setUnsignedLong(long index, long value) {
    imebraJNI.WritingDataHandler_setUnsignedLong(swigCPtr, this, index, value);
  }

  public void setDouble(long index, double value) {
    imebraJNI.WritingDataHandler_setDouble(swigCPtr, this, index, value);
  }

  public void setString(long index, String value) {
    imebraJNI.WritingDataHandler_setString(swigCPtr, this, index, value);
  }

  public void setDate(long index, Date date) {
    imebraJNI.WritingDataHandler_setDate(swigCPtr, this, index, Date.getCPtr(date), date);
  }

  public void setAge(long index, Age age) {
    imebraJNI.WritingDataHandler_setAge(swigCPtr, this, index, Age.getCPtr(age), age);
  }

}
